version: "3.7"
services:
  backend:
    build: backend
    env_file:
      - backend/.env
    ports:
      - 8000:8000
  frontend:
    build: frontend
    env_file:
      - frontend/.env.local
    ports:
      - 3000:3000
