version: "3.7"
services:
  backend:
    build: backend
    env_file:
      - backend/.env
    ports:
      - 27725:8000
  frontend:
    build:
      context: frontend
      args:
        NEXT_PUBLIC_BASE_URL: ${NEXT_PUBLIC_BASE_URL:-http://localhost:27725}
    env_file:
      - frontend/.env.local
    ports:
      - 27724:3000
