name: Prettify Code

on:
  pull_request:
  push:

jobs:
  prettier:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}

      - name: Prettify code
        uses: creyD/prettier_action@v4.6
        with:
          prettier_options: --write **/*.{js,mjs,md} --print-width 100
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
